# Write a github actions workflow that does the following:
# Tests the code using Jest and the pre-built `npm run test` command
# Builds a docker image using the Dockerfile that you have written
# Pushes the docker image to your GitHub Container Registry repository
# Releases your newly pushed image to your Railway service using the Railway CLI

name: take-home-assessment-5123213

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm run test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}




#     - name: Install Railway CLI
#       run: curl https://get.railway.app | bash
#     - name: Login to Railway
#       run: railway login
#       env:
#         RAILWAY_USERNAME: ${{ secrets.RAILWAY_USERNAME }}
#         RAILWAY_PASSWORD: ${{ secrets.RAILWAY_PASSWORD }}
#     - name: Release to Railway
#       run: railway run "railway release ghcr.io/abhishekbhogal/takehome-assessment-copy:latest"
