# Write a github actions workflow that does the following:
# Tests the code using Jest and the pre-built `npm run test` command
# Builds a docker image using the Dockerfile that you have written
# Pushes the docker image to your GitHub Container Registry repository
# Releases your newly pushed image to your Railway service using the Railway CLI

name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Test code
        run: npm run test

      - name: Build Docker image
        run: docker build -t node-docker-veryable-copy .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag node-docker-veryable-copy ghcr.io/${{ github.repository }}/node-docker-veryable-copy:${{ github.sha }}
          docker push ghcr.io/${{ github.repository }}/node-docker-veryable-copy:${{ github.sha }}
    
      - name: Install Railway
        run: npm i -g @railway/cli
      
      - name: Authenticate with Railway CLI
        run: railway login --no-prompt




